version: '3'

tasks:
  default:
    cmds:
      - task -l
    silent: true

  test:
    desc: Run tests.
    cmds:
      - go test -short ./...

  localize:
    desc: Extract localized strings.
    cmds:
      - xspreak -D ./ -o internal/i18n/locale/inpxer.pot -t "ui/templates/*.gohtml"

  build-testing:
    desc: Build testing version.
    cmds:
      - go build -ldflags="-s -w -X main.version=testing"
